### PR TITLE
update Blender to 4.2.0

### PR DESCRIPTION
**Pull request by kevinsmia1939**

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
@lirtistan @Beryesa
Could you let me know if this build works fine?

**Comment by lirtistan** [comment]
I test on my Ubuntu 22.04LTS right now!

**Comment by Beryesa** [comment]
Eevee Next and Cycles CUDA/Optix works, no HIP but that's not new. Can't test oneapi :sweat_smile: 
Drag&Drop from the new extensions website crashed it but that might be on Blender than on the flatpak version? Gotta test the tarball later :thinking: 
Libdecor doesn't pick up the dark theme on Gnome in Wayland but it's not really important.
All fine by me, nothing major! :D

**Comment by lirtistan** [comment]
After one hour of gambling with Realtime-Displacement in EEVEE, i can confirm it works...

Screenshot from 2024-07-17 18-12-38

I just noticed a freeze at the first startup (took a minute or so to became responsive), because there is a new setting that let you configure the amount of EEVEE shader compilation subprocesses (witch the devs set to ZERO by default), after increasing that value to 32, EEVEE became quickly responsive. (see Screenshot below)
 
Screenshot from 2024-07-17 18-17-43

Sorry can currently not test on my bigger setup (this test was made on my 14`inch laptop with integrated AMD graphics, OpenGL core 4.6 profile)

**Comment by lirtistan** [comment]
https://github.com/user-attachments/assets/2d8bd131-87f5-4c77-b3e8-488c1eea867e

**Comment by Beryesa** [comment]
I think it's just warning, have you permitted online access in the "Get Extensions" tab? It should refresh after the first use.

**Comment by kevinsmia1939** [comment]
> Eevee Next and Cycles CUDA/Optix works, no HIP but that's not new. Can't test oneapi 😅 Drag&Drop from the new extensions website crashed it but that might be on Blender than on the flatpak version? Gotta test the tarball later 🤔 Libdecor doesn't pick up the dark theme on Gnome in Wayland but it's not really important. All fine by me, nothing major! :D

Hi, drag and drop extension from website works for me, maybe its the extension itself that cause the crash?
Anyway, I'm merging now.

**Comment by lirtistan** [comment]
> I think it's just warning, have you permitted online access in the "Get Extensions" tab? It should refresh after the first use.
No i havn't. I was just playing with the new Displacements under EEVEE.

**Comment by Beryesa** [comment]
Thanks <3

**Comment by lirtistan** [comment]
Also Thank you very much ❤️

**Pull request merged**
