### PR TITLE
Build from source

### PR DESCRIPTION
**Pull request by hfiguiere**
@bochecha this is on top of your changes.

It currently fail on Blender that want Python 3.10.
Disabling Python al together fail much earlier.

### CODE REVIEW

**Comment by hfiguiere** [comment]
The error I get locally is different, but related to Python as well:

```
[3997/4405] Building C object source/blender/python/intern/CMakeFiles/bf_python.dir/bpy.c.o
FAILED: source/blender/python/intern/CMakeFiles/bf_python.dir/bpy.c.o 
/run/ccache/bin/cc -DBUILD_DATE -DNDEBUG -DWITH_ALEMBIC -DWITH_AUDASPACE -DWITH_AVI -DWITH_BULLET -DWITH_CINEON -DWITH_COLLADA -DWITH_COMPOSITOR -DWITH_CYCLES -DWITH_CYCLES_EMBREE -DWITH_DDS -DWITH_FFMPEG -DWITH_FLUID -DWITH_FREESTYLE -DWITH_HDR -DWITH_INTERNATIONAL -DWITH_LIBMV -DWITH_MOD_REMESH -DWITH_OCEANSIM -DWITH_OCIO -DWITH_OPENAL -DWITH_OPENEXR -DWITH_OPENGL -DWITH_OPENIMAGEIO -DWITH_OPENJPEG -DWITH_OPENSUBDIV -DWITH_OPENVDB -DWITH_PUGIXML -DWITH_PULSEAUDIO -DWITH_SDL -DWITH_SNDFILE -DWITH_TIFF -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D__LITTLE_ENDIAN__ -D__MMX__ -D__SSE2__ -D__SSE__ -I/run/build/blender/source/blender/python -I/run/build/blender/source/blender/blenkernel -I/run/build/blender/source/blender/blenlib -I/run/build/blender/source/blender/blenloader -I/run/build/blender/source/blender/blentranslation -I/run/build/blender/source/blender/depsgraph -I/run/build/blender/source/blender/editors/include -I/run/build/blender/source/blender/gpu -I/run/build/blender/source/blender/imbuf -I/run/build/blender/source/blender/makesdna -I/run/build/blender/source/blender/makesrna -I/run/build/blender/source/blender/windowmanager -I/run/build/blender/intern/clog -I/run/build/blender/intern/guardedalloc -I/run/build/blender/intern/mantaflow/extern -I/run/build/blender/intern/opencolorio -I/run/build/blender/_flatpak_build/source/blender/makesrna -I/run/build/blender/intern/cycles/blender -I/run/build/blender/source/blender/freestyle/intern/python -I/run/build/blender/intern/openvdb -I/run/build/blender/source/blender/io/alembic -I/run/build/blender/source/blender/imbuf/intern/oiio -I/run/build/blender/intern/opensubdiv -isystem /usr/include/python3.9 -isystem /usr/include/SDL2 -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5 -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -fopenmp -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -fmacro-prefix-map="/run/build/blender/"="" -fmacro-prefix-map="/run/build/blender/_flatpak_build/"="" -Wno-maybe-uninitialized -O2 -g -DNDEBUG -MD -MT source/blender/python/intern/CMakeFiles/bf_python.dir/bpy.c.o -MF source/blender/python/intern/CMakeFiles/bf_python.dir/bpy.c.o.d -o source/blender/python/intern/CMakeFiles/bf_python.dir/bpy.c.o -c /run/build/blender/source/blender/python/intern/bpy.c
In file included from /run/build/blender/source/blender/python/intern/bpy.c:33:
/run/build/blender/source/blender/python/intern/bpy_capi_utils.h:10:4: error: #error "Python 3.10 or greater is required, you'll need to update your Python."
   10 | #  error "Python 3.10 or greater is required, you'll need to update your Python."
      |    ^~~~~
[4000/4405] Linking CXX static library lib/libbf_intern_cycles.a
```

**Comment by hfiguiere** [comment]
opencolorio needs a patch.

**Comment by hfiguiere** [comment]
I get some Python errors on startup. Not sure what's causing them though.

**Comment by Zenith222** [comment]
May I ask what is the point of this change? Blender.org provides trusted binaries which can be verified with a SHA256 or SHA512 hash for security purposes. Building Blender from source on every user's machine is a waste of time and energy for no practical benefit.

**Comment by Zenith222** [comment]
> 

I appreciate the clarification.

**Comment by hfiguiere** [comment]
it would be nice to have this build tested by people that use this more than I do. (i don't).

**Comment by hfiguiere** [comment]
closing this. nobody seems to be interested.

**Comment by theofficialgman** [comment]
Hoping this can be reopened and considered.
Would be highly appreciated by the arm64 Linux community.

**Pull request closed without merging**
