### PR TITLE
WIP: Blender 2.8

### PR DESCRIPTION
**Pull request by bochecha**
Blender 2.8 isn't released yet, this is just to be ready when it is, and because @jimmac asked nicely.

### CODE REVIEW

**Comment by bochecha** [comment]
testbot, build

**Comment by alexlarsson** [comment]
testbot, build

**Comment by alexlarsson** [comment]
sorry, i cancelled this build due to updating the buildbot

**Comment by bochecha** [comment]
Superceded by #21.

**Comment by bochecha** [comment]
I'd like to take advantage of the new support for Beta builds in Flathub, which mean naming the branch "beta".

Since I had named this branch differently, I'm closing this in favour of #22

**Pull request closed without merging**
